version: "3.8"

services:
  db:
    image: postgres:14
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config app/logging_config.yaml"

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    entrypoint: >
      sh -c "pytest --capture=tee-sys --log-cli-level=INFO tests/ | tee logs/test_results.log"
