version: 1
formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"

handlers:
  file:
    class: logging.FileHandler
    filename: logs/api.log
    formatter: default

loggers:
  uvicorn:
    level: INFO
    handlers: [file]
    propagate: no

root:
  level: INFO
  handlers: [file]
